version: "3.8"

services:
    web:
        container_name: web
        build: .
        ports:
            - "5000:5000"
        environment:
            - PYTHONUNBUFFERED=1
    # Proxy (Nginx)
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web